### ISSUE TITLE
Issue with PDF reports

### ISSUE THREAD

**Issue by dmgbk** [findsorguk/findsorguk#1004]
We have just had a major IT refresh at Norfolk County Council, including new laptops and updated software.  We have moved to a Windows 7 operating system and are still using Firefox (Version 37.0.2) but have come across an issues while using the PDF report format button. We now use Adobe Acrobat DC and the IT contractors say that it is likely to be because the PDF report is not written to be compatible with Acrobat DC.  Is this the case? If so, are you able to fix the issue please.  The Finds team use this regularly to give data to finds at club meetings. Please find a screenshot attached. Thanks very much.
[PASAcrobatDCIssue.docx](https://github.com/findsorguk/findsorguk/files/50622/PASAcrobatDCIssue.docx)

**Comment by s-moon** [comment]
Hi @dmgbk,

We are experiencing the same problem, so it's definitely a wider issue than for you. 

In the mean time, I see that you can export as CSV which, although not ideal, might be enough whilst you wait for a proper fix.

I've added this issue to our support queue and will be looking in to it.

Thanks for raising it,

Steve

**Comment by portableant** [comment]
Maybe this line is playing up:
https://github.com/findsorguk/findsorguk/blob/a8df6043f3936de4f1289e00f0901dff3f3f6edc/app/modules/database/views/scripts/ajax/pdf.phtml#L17

**Comment by rjw57** [comment]
Cropped screenshot from issue report below. I recommend that an admin edit the original issue report to remove the Word document link because the full screenshot includes personally identifying information and an Outlook screenshot with a partially composed email and (perhaps) personal email addresses.

![issue-1004-screenshot](https://cloud.githubusercontent.com/assets/146860/11655516/5975fd8a-9da6-11e5-8329-dc3a3ce9886d.png)

**Comment by s-moon** [comment]
I wasn't able to see that in the Word document but removed the link anyway. User has confirmed that the issue is now resolved.
