### ISSUE TITLE
Issue to submit error report for records for 'Grid ref' and 'Data Problems'

### ISSUE THREAD

**Issue by Minakshi-Chidrawar** [findsorguk/findsorguk#1192]
![image](https://user-images.githubusercontent.com/22420871/42386893-ab594b66-8138-11e8-9ff9-414b6cc819b1.png)

The record should be inserted into the table 'errorreports' with values as 'Grid ref issues' and 'Data problems' for the column comment_type

Try to report a mistake for any record with either one of error 'Grid reference wrong' or 'Data problems' as Error type.

Change 'Grid reference issues' => 'Grid reference wrong' to 'Grid reference issues' => 'Grid ref wrong' from 
https://github.com/findsorguk/findsorguk/blob/b2d4eaa7705f87c98a429b17e5f6f8473b672db0/app/forms/CommentOnErrorFindForm.php#L69

And change 'Data problems apparent' => 'Data problems' to 'Data problems app' => 'Data problems' of the
https://github.com/findsorguk/findsorguk/blob/b2d4eaa7705f87c98a429b17e5f6f8473b672db0/app/forms/CommentOnErrorFindForm.php#L73

**Comment by portableant** [comment]
Simpler fix would be to increase the length allowed in the MySQL column. Current column max characters is 20. You then maintain the groupings for already entered data too.

**Comment by s-moon** [comment]
Either way @portableant , we can't stick to the groupings because at some point, it allowed the data into the table without failing, just truncating.

|comment_type| count(*)|
|---------------|-------------|
|Data problems appare| 542|
|Grid reference issue| 508

Another approach @Minakshi-Chidrawar is to change:

'Grid reference issues' => 'Grid reference wrong' >>>>> 'Grid reference issue' => 'Grid reference wrong'

No 's'.

and 

'Data problems apparent' => 'Data problems' >>>>> 'Data problems' => 'Data problems'

Removing the 'apparent' plus then following up with a SQL update statement to fix the existing stuff.

```
UPDATE errorreports SET comment_type = 'Data Problems' WHERE comment_type = 'Data problems appare';
```

**Comment by portableant** [comment]
Simple to fix +1

**Comment by portableant** [comment]
PS - may want to edit that first screen shot for personal data - IP and usernames.
