### ISSUE TITLE
export of hoard summary incomplete

### ISSUE THREAD

**Issue by eghey2** [findsorguk/findsorguk#914]
Exporting a hoard summary from within a hoards record only returns the first few lines, not the whole summary. Reported by K Robbins on 12th June and confirmed by testing.

**Comment by portableant** [comment]
I believe that this is now fixed. The problem was quite simple, either @mchesterkadwell or me had made a mistake on the add function for coin summaries. If you added a coin, the data was not added to the search index, if you updated that coin summary record, it then did add it. So unless you updated a record, they would be absent for the export to run. So closed this issue in 8f9f1125ec84e49fae0938b3c394890fb7a1e547
