### ISSUE TITLE
Subsequent action field

### ISSUE THREAD

**Issue by irichardson77** [findsorguk/findsorguk#942]
The subsequent action field of the database record has a default setting of 'Returned to finder' but that is not always the case. There are many records of Treasure finds that have not been updated with the proper 'subsequent action'. It might be better if the default was blank, at least for Treasure finds (i.e. activated when user ticks the Treasure box).

**Comment by portableant** [comment]
Treasure records as an overall proportion of records is so small that this isn't worth implementing. Get it right first time?

**Comment by irichardson77** [comment]
True but…I suppose most FLOs are conditioned not to fiddle with this field because it already has the default in it. Does it really need to be completed for most finds? I think most people would assume that non-Treasure finds are returned to the finder anyway, with the very occasional non-Treasure find acquired by a museum.  I will remind the FLOs anyway at some point.

Thank you

**Comment by portableant** [comment]
It was introduced as a field so that we could attempt to track whether private collections or museums were gathering new finds. Of course it is useless if no one fills it in properly. Like all the other fields. To make mandatory for T finds would take a good bit of programming, couple of days. Is it really worth it?

**Comment by irichardson77** [comment]
No, you’re right, I’m sure it isn’t!
